plugins:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-performance

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.4
  SuggestExtensions: false
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'bin/**/*'
    - 'vendor/**/*'
    - 'node_modules/**/*'
    - 'tmp/**/*'

# Длина строки
Layout/LineLength:
  Max: 120
  Exclude:
    - 'spec/**/*'

# Отступы
Layout/IndentationWidth:
  Width: 2

# Методы
Style/MethodDefParentheses:
  EnforcedStyle: require_parentheses

# Строки
Style/StringLiterals:
  EnforcedStyle: single_quotes

# Хеши
Style/HashSyntax:
  EnforcedStyle: ruby19_no_mixed_keys

# Методы
Style/MethodCallWithArgsParentheses:
  EnforcedStyle: require_parentheses

# Rails специфичные правила
Rails:
  Enabled: true

Rails/BulkChangeTable:
  Enabled: true

Rails/FilePath:
  EnforcedStyle: arguments

# RSpec правила
RSpec:
  Enabled: true

RSpec/ExampleLength:
  Max: 20

RSpec/MultipleExpectations:
  Max: 5

# Производительность
Performance:
  Enabled: true

Performance/StringReplacement:
  Enabled: true
