# Database Configuration for Beyond Home Application
# 
# This file configures the database connections for different environments.
# We use PostgreSQL with the following naming convention:
# - beyond_home_development
# - beyond_home_test  
# - beyond_home_production
#
# Database credentials are stored in environment variables:
# - POSTGRES_USERNAME
# - POSTGRES_PASSWORD

# Default configuration shared across all environments
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

# Development Environment
# Database: beyond_home_development
development:
  <<: *default
  database: beyond_home_development
  username: <%= ENV.fetch("POSTGRES_USERNAME", "postgres") %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD", "postgres") %>
  host: <%= ENV.fetch("POSTGRES_HOST", "localhost") %>
  port: <%= ENV.fetch("POSTGRES_PORT", "5432") %>

# Test Environment  
# Database: beyond_home_test
test:
  <<: *default
  database: beyond_home_test
  username: <%= ENV.fetch("POSTGRES_USERNAME", "postgres") %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD", "postgres") %>
  host: <%= ENV.fetch("POSTGRES_HOST", "localhost") %>
  port: <%= ENV.fetch("POSTGRES_PORT", "5432") %>

# Production Environment
# Database: beyond_home_production
# Uses environment variables for security
production:
  <<: *default
  database: beyond_home_production
  username: <%= ENV.fetch("POSTGRES_USERNAME", "beyond_home") %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD") %>
  host: <%= ENV.fetch("POSTGRES_HOST", "localhost") %>
  port: <%= ENV.fetch("POSTGRES_PORT", "5432") %>
  # Note: In production, consider using DATABASE_URL environment variable
  # url: <%= ENV['DATABASE_URL'] %>
